### ISSUE TITLE
WASM Friendliness - subprocess call method refactoring

### ISSUE THREAD

**Issue by daniel-ji** [niemasd/GEMF#1]
For overriding the call function in the online browser version, it is possible only when `from subprocess import call` is changed to `import subprocess` and instead of `call([gemf_path], stdout=log_f)`, `subprocess.call([gemf_path], stdout=log_f)` is used. 

Thank you!

**Comment by niemasd** [comment]
Patched in https://github.com/niemasd/GEMF/commit/02458d09192bf8fe171facd662182dbc8f7b2d2e
